# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6b7fba2755f4dd3c934bda8a6ab2b5ff86c0a8fb900d9a6c87b60f4e210b740a18066d4695129937eac5593b265590d7a9869b02a7ea0efa49db48dd52c1a3f3

test:
  secret_key_base: 3960f2c7009d96c21f45444d142ce9df865f0f252bb336a112c400b2fd549fa5dee5be262deb40e9284fef38b556f90accd7bcf0d3fd5c0e2ae2fa74f9129152

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
